BnB/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hosting/',include('hosting.urls')),
    path('accounts/',include('accounts.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("signup/",views.signup, name="signup"),
    path("login/",views.loginPage,name="login"),
    path("logout/",views.logoutPage,name="logout")
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username","email","password1","password2"]
        
        

accounts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import  render

from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from .forms import CreateUserForm
from .decorators import unautheticated_user

# Create your views here.
@unautheticated_user
def signup(request):
    form = CreateUserForm()
    if request.method == 'POST':
     form = CreateUserForm(request.POST)
     if form.is_valid():
         form.save()
         user =form.cleaned_data.get("username")
         messages.success(request,"Account successfully created for "+ user)
         
         return HttpResponseRedirect(reverse("accounts:login"))
    return render(request,"accounts/signup.html",{"form":form})

@unautheticated_user
def loginPage(request):
    if request.method=="POST":
       username= request.POST.get("username")
       password= request.POST.get("password")
        
       user = authenticate(request,username=username,password=password)
        
       if user is not None:
           login(request,user)
           messages.success(request,"Welcome "+ username)
           return HttpResponseRedirect(reverse("hosting:dashboard"))
       else:
           messages.info(request,"Username or password is incorrect")
           
    
    return render(request,"accounts/login.html")


def logoutPage(request):
    logout(request)
    return HttpResponseRedirect(reverse("accounts:login"))

accounts/templates/accounts/login.html
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>

    body {font-family: Arial, Helvetica, sans-serif;}
    * {box-sizing: border-box;}
    .alert {
  padding: 20px;
  background-color:limegreen;
  color: white;
}

.closebtn {
  margin-left: 15px;
  color: white;
  font-weight: bold;
  float: right;
  font-size: 22px;
  line-height: 20px;
  cursor: pointer;
  transition: 0.3s;
}

.closebtn:hover {
  color: black;
}
    .input-container {
      margin-left: 16.5em;
      display: -ms-flexbox; /* IE10 */
      display: flex;
      width: 50%;
      margin-bottom: 15px;
    }
    
    .icon {
      padding: 10px;
      background: dodgerblue;
      color: white;
      min-width: 50px;
      text-align: center;
    }
    
    .input-field {
      width: 100%;
      padding: 10px;
      outline: none;
    }
    
    .input-field:focus {
      border: 2px solid dodgerblue;
    }
    
    /* Set a style for the submit button */
    .btn {
      margin-left: 20em;
      background-color: dodgerblue;
      color: white;
      padding: 15px 20px;
      border: none;
      cursor: pointer;
      width: 50%;
      opacity: 0.9;
    }
    
    .btn:hover {
      opacity: 1;
    }
  
  
    span{
      margin-left: 20em;
    }
  
    h2{
      margin-left: 20em;
    }
    </style>
{% block title %}
<h2>Login </h2>
  
{% endblock title %}



<form action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
   
  
    <div class="input-container">
      <i class="fa fa-user icon" ></i>
      <input class="input-field" type="text" placeholder="Username" name="username">
    </div>
  
    
  
    <div class="input-container">
      <i class="fa fa-key icon"></i>
      <input class="input-field" type="password" placeholder="Password" name="password">
    </div>
   
    <button type="submit" class="btn">Login</button>
  </form>
  
  
  
  
  
  <span>Don't have an account?<a href="{% url 'accounts:signup' %}">Sign up</a></span>
  
  
    {% for message  in messages  %}
   
   

    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
        <strong>Success</strong> <p>{{message}}</p>    
      </div>
      {% endfor %}
  

accounts/templates/accounts/signup.html
{% load static  %}


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
  body {font-family: Arial, Helvetica, sans-serif;}
  * {box-sizing: border-box;}
  
  .input-container {
    margin-left: 16.5em;
    display: -ms-flexbox; /* IE10 */
    display: flex;
    width: 50%;
    margin-bottom: 15px;
  }
  
  .icon {
    padding: 10px;
    background: dodgerblue;
    color: white;
    min-width: 50px;
    text-align: center;
  }
  
  .input-field {
    width: 100%;
    padding: 10px;
    outline: none;
  }
  
  .input-field:focus {
    border: 2px solid dodgerblue;
  }
  
  /* Set a style for the submit button */
  .btn {
    margin-left: 20em;
    background-color: dodgerblue;
    color: white;
    padding: 15px 20px;
    border: none;
    cursor: pointer;
    width: 50%;
    opacity: 0.9;
  }
  
  .btn:hover {
    opacity: 1;
  }


  span{
    margin-left: 20em;
  }

  h2{
    margin-left: 20em;
  }
  </style>




<form action="{% url 'accounts:signup' %}" method="post" >
  {% csrf_token %}
 
  <span><h2>Register Form</h2></span>
  <div class="input-container">
    <i class="fa fa-user icon" ></i>
    <input class="input-field" type="text" placeholder="Username" name="username">
  </div>

  <div class="input-container">
    <i class="fa fa-envelope icon"></i>
    <input class="input-field" type="text" placeholder="Email" name="email">
  </div>

  <div class="input-container">
    <i class="fa fa-key icon"></i>
    <input class="input-field" type="password" placeholder="Password" name="password1">
  </div>
  <div class="input-container">
    <i class="fa fa-key icon"></i>
    <input class="input-field" type="password" placeholder="Confirm Password" name="password2">
  </div>
  <button type="submit" class="btn">Register</button>
</form>





<span>Already have an account? <a href="{% url 'accounts:login' %}">Sign in</a></span>


  {% for message  in messages  %}
  <p>{{message}}</p>    
  {% endfor %}