BnB/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hosting/',include('hosting.urls')),
    path('accounts/',include('accounts.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("signup/",views.signup, name="signup"),
    path("login/",views.loginPage,name="login"),
    path("logout/",views.logoutPage,name="logout")
]

hosting/urls.py
from django.urls import path
from . import views


app_name='hosting'

urlpatterns = [
    #rooms urls
    path('',views.rooms,name="homepage"),
    path('view-rooms/',views.rooms,name="view-rooms"),
    path("view-my-rooms/",views.userRooms,name="dashboard"),
    path('create-room/',views.create_room,name="createroom"),
    path('rooms/<int:pk>/',views.room,name="viewroom"),
    path('edit-room/<int:pk>/',views.edit_room,name="editroom"),
    path('delete/<int:pk>/',views.delete_room, name="delete_room"),
    
    #booking url
    path('book-room/<int:pk>/<int:user_id>/', views.book_room, name='book-room'),
    path("bookings/",views.show_bookings,name="bookings"),
    path("show-my-bookings/",views.show_my_booking,name="show-my-bookings")
]
 

hosting/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Room(models.Model):
    image =models.ImageField(upload_to='images/')
    name =models.CharField(max_length=50)
    description = models.TextField()
    location = models.CharField(max_length=25)
    price = models.FloatField()
    occupied = models.BooleanField(default=False)
    is_cleaned = models.BooleanField()
    owner = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    
    def __str__(self):
        return self.name 
class Client(models.Model):
    contact= models.IntegerField()
    name = models.ForeignKey(User,on_delete=models.CASCADE,default=1 )
    
    client = None  # client field should be set after saving the object

    def __str__(self):
        return self.name.username  # return the username of the related User object

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.client = self.name.id  # set the client field to the id of the related User object
        super().save(*args, **kwargs) 
        # save the object again to update the client field
class Booking(models.Model):
    client = models.ForeignKey(Client,on_delete=models.CASCADE)
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    duration = models.IntegerField()
    begin = models.DateField(auto_now=False, auto_now_add=False)
    end = models.DateField(auto_now=False, auto_now_add=False)
    amount =models.FloatField()
    
    def __str__(self):
        return self.room
    
    class Meta:
        ordering =['room','begin']

class Review(models.Model):
    description = models.TextField()
    user= models.ForeignKey(Client, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.description
    

hosting/forms.py
from django import forms
from .models import Room,Booking,User
from django.shortcuts import get_object_or_404

    
class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ['image', 'name', 'description', 'location', 'price', 'occupied', 'is_cleaned', 'owner']




class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['client','room','begin','end']
        
        widgets = {
            'begin': forms.DateInput(attrs={'type': 'date'}),
            'end': forms.DateInput(attrs={'type': 'date'}),
        }
        
        

hosting/views.py
from django.shortcuts import render, get_object_or_404
from .models import Room,Booking, Client
from .forms import RoomForm,BookingForm
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db import transaction
from django.db.models import Q
from datetime import datetime, timedelta


# Create your views here.


def rooms(request):
    rooms = Room.objects.all()

    return render(request, "hosting/display_rooms.html", {"rooms": rooms})


def room(request, pk):
    room = get_object_or_404(Room, id=pk)

    return render(request, "hosting/room_detail.html", {"room": room})


@login_required(login_url=reverse_lazy("accounts:login"))
def create_room(request):
    if request.method == "POST":
        form = RoomForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("hosting:dashboard"))
    else:
        form = RoomForm()
    return render(request, "hosting/create_room.html", {"form": form})


@login_required(login_url=reverse_lazy("accounts:login"))
def edit_room(request, pk):
    room_to_edit = get_object_or_404(Room, pk=pk)

    if request.method == "POST":
        form = RoomForm(request.POST, request.FILES, instance=room_to_edit)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("hosting:dashboard"))
    else:
        form = RoomForm(instance=room_to_edit)
    return render(
        request, "hosting/edit_room.html", {"form": form, "name": room_to_edit.name}
    )


@login_required(login_url=reverse_lazy("accounts:login"))
def delete_room(request, pk):
    room = Room.objects.get(id=pk)
    room.delete()
    return HttpResponseRedirect(reverse("hosting:dashboard"))


@login_required(login_url=reverse_lazy("accounts:login"))
def userRooms(request):
    my_id = request.user.id
    owner = User.objects.get(id=my_id)
    my_rooms = Room.objects.filter(owner=owner)
    my_bookings = Booking.objects.filter(room__owner=owner)
    paginator = Paginator(my_rooms, 1)
    page = request.GET.get("page")
    items = paginator.get_page(page)
    return render(request, "hosting/dashboard.html", {"rooms": items,"bookings":my_bookings})



@login_required(login_url=reverse_lazy("accounts:login"))
@transaction.atomic
def book_room(request,pk,user_id):
    room_id =request.POST.get('room')
    room = get_object_or_404(Room, pk=room_id)
    client_id=request.POST.get('client')
    client = get_object_or_404(Client, pk=client_id)
    
    if request.method == "POST":
        form = BookingForm(request.POST)
        
        if form.is_valid():
            booking = form.save(commit=False)
            begin_date_string = request.POST.get('begin')
            end_date_string = request.POST.get('end')
        
            begin_date = datetime.strptime(begin_date_string, '%Y-%m-%d')
            end_date = datetime.strptime(end_date_string, '%Y-%m-%d')
        
            duration = (end_date - begin_date).days
            booking.amount = room.price * duration
            booking.duration = duration
            booking.client = client
            booking.room = room
            
            # Check for double booking
            existing_bookings = Booking.objects.filter(
                Q(begin__lt=end_date) & Q(end__gt=begin_date) & Q(room=room)
            )
            if existing_bookings:
                message = f"Room {room} is already booked from {begin_date} to {end_date}."
                return render(request, "hosting/book_room.html", {"form": form, "error_message": message})
            
            # Save the booking and mark the room as occupied
            booking.save()
            room.occupied = True
            room.save()
          
            return HttpResponseRedirect(reverse("hosting:bookings"))
    else:
        form = BookingForm()
    
    return render(request, "hosting/book_room.html", {"form": form})


#list bookings
def show_bookings(request):
    bookings = Booking.objects.all()
    return render(request,"hosting/bookings.html",{"bookings":bookings})

def show_my_booking(request):
    my_id = request.user.id
    owner = User.objects.get(id=my_id)
    my_rooms = Room.objects.filter(owner=owner)
    my_bookings = Booking.objects.filter(room__owner=owner)
    return render (request,"hosting/my_bookings.html",{"my-bookings":my_bookings})

hosting/templates/hosting/book_room.html
{% load  static  %}
<link rel="stylesheet" href="{%  static 'hosting/bookroom.css'%}">

<div class="alert">
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    {{error_message}}
  </div>
<form  method="post" >
    {% csrf_token %}
    
    
    <table class="book-room">
        <tr>
            <th>{{form.client.label_tag}}</th>
            <th>{{form.room.label_tag}}</th>
            <th>{{form.begin.label_tag}}</th>
            <th>{{form.end.label_tag}}</th>
        </tr>
        <tr>
            
            <td>{{ form.client }}</td>
            <td>{{form.room}}</td>
            <td>{{form.begin}}</td>
            <td>{{form.end}}</td>
        </tr>
    </table>
        <input type="submit" value="Book" id="button">
 </form>

hosting/templates/hosting/bookings.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bookings</title>
    <link rel="stylesheet" href="{% static 'hosting/bookings.css' %}">
</head>
<body>
  {% include 'topnav.html' %}
   
    <table class="booking">
        <tr>
            <th>Room</th>
            <th>Client</th>
            <th>From</th>
            <th>To</th>
            <th>Duration</th>
           
        </tr>
    {% for booking in bookings  %}
   
        <tr>
            <td>{{booking.room}}</td>
            <td>{{booking.client}}</td>
            <td>{{booking.begin}}</td>
            <td>{{booking.end}}</td>
            <td>{{booking.duration}}</td>
        </tr>
        {% endfor %}
    </table>
      
   
</body>
</html>

hosting/templates/hosting/create_room.html
{% extends 'index.html' %}

{% load  static  %}
<link rel="stylesheet" type="text/css" href="{%  static 'hosting/createroom.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'hosting/index.css' %}">

{% block content %}
  <div>
    <h2>Fill in the details for the new room</h2>
    <form method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
    
        <table >
            <tr>
                <th>{{ form.image.label_tag }}</th>
                <th>{{ form.name.label_tag }}</th>
                <th>{{form.description.label_tag}}</th>
                <th>{{form.price.label_tag}}</th>
                <th>{{form.location.label_tag}}</th>
                <th>{{form.owner.label_tag}}</th>
                
            </tr>
            <tr>
                <td>{{ form.image}}</td>
                <td>{{ form.name }}</td>
                <td>{{form.description}}</td>
                <td>{{form.price}}</td>
                <td>{{form.location}}</td>
                <td>{{form.owner}}</td>
            </tr>
    
           
        </table>
        <input type="submit" value="Submit">
    
    </form>
    {% endblock content %}
    
       
    
    
    
  </div>

hosting/templates/hosting/dashboard.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{request.user}} Dashboard</title>
    <link rel="stylesheet" href="{% static 'hosting/dashboard.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
</head>
<body>
    {% include 'topnav.html' %}
    {% block title %}
     <div class="title">
        <span><h4>{{request.user}}'s  Rooms</h4></span>
       <div id="addroom"><a href="{% url 'hosting:createroom' %}" ><span class="material-symbols-outlined">
        add
        </span>Add Room</a></div>
    </div> 

    {% endblock title %}

 {% block content %}
 {% if rooms.has_previous %}
 <a href="?page={{ rooms.previous_page_number }}" id="previous">Previous Page</a>
{% endif %}

 {% for room in rooms %}
 <div class="room">
    <div id="roomimage">
    <img src="{{room.image.url}}" alt="room-image" id="image">
    </div>
    <div id="content">
    <h3>{{room.description}}</h3>
    <h3>Price: USD {{room.price}}</h3>
    </div>
     </div>
 {% endfor %}
 {% if rooms.has_next %}
  <a href="?page={{ rooms.next_page_number }}">Next</a>
{% endif %}
 {% endblock content %}
   
</body>
</html>

hosting/templates/hosting/display_rooms.html
{% load static  %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Rooms</title>
    <link rel="stylesheet" type="text/css" href='{% static "hosting/displayrooms.css" %}'>
   
    <script>
        function goBack() {
          window.history.back();
        }
        </script>
    
</head>
<body >
    <button onclick="goBack()">Go Back</button>

<div class="add">
    <button class="button" onclick="window.location.href='{% url 'hosting:createroom' %}'"  id="add-room"> <img src="{% static 'hosting/images/add.svg'%}" alt="add svg" id="svg"  > ADD ROOM</button>
</div>


<h2>Welcome {{request.user}}</h2>
<span id="logout"><a href="{% url 'accounts:logout' %}">Logout</a></span>

<div class="grid-container">
 
    {% for room in  rooms %}
    <div class="grid-item">
      <div class="card">
          <img src="{{room.image.url }}" alt="room image" class="img">
          
          <div class="container">
            <h5>@ {{room.owner}}</h5>
            <h4>Room {{room.name}}</h4>
            <h4><b>Description: </b></h4> 
            <p>{{room.description}}</p> 

          {% if request.user == room.owner %}
          <button class="button"  onclick="window.location.href='{% url 'hosting:viewroom' room.id %}'"  >View More</button>
            <button class="button" id="delete" onclick="window.location.href='{% url 'hosting:delete_room' room.id %}'" >Delete</button>
          {% else %}
          <button class="button"  onclick="window.location.href='{% url 'hosting:viewroom' room.id %}'"  >View More</button>
          {% endif %}

            
          </div>
        </div>
    </div>
      
    {% endfor %}
  
    
</div>

  
  


</body>
</html>

hosting/templates/hosting/edit_room.html
{% block title %}
  <h2>Edit room {{name}}</h2>
{% endblock title %}


{% block content %}

<form  method="post" enctype="multipart/form-data">
{% csrf_token %}

    <table class="edit">
        <tr>
            <th>{{ form.image.label_tag }}</th>
            <th>{{ form.name.label_tag }}</th>
            <th>{{form.description.label_tag}}</th>
            <th>{{form.price.label_tag}}</th>
            <th>{{form.location.label_tag}}</th>
            <th>{{form.owner.label_tag}}</th>
            
            
        </tr>
        <tr>
            <td>{{ form.image}}</td>
            <td>{{ form.name }}</td>
            <td>{{form.description}}</td>
            <td>{{form.price}}</td>
            <td>{{form.location}}</td>
            <td>{{form.owner}}</td>
        </tr>

       
    </table>
    <input type="submit" value="Submit">
</form>
{{form.errors}}

{% endblock content %}

hosting/templates/hosting/index.html
{% load static%} 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BednBreakfast </title>
    <link rel="stylesheet" type="text/css" href="{% static 'hosting/index.css' %}">
</head>
<body>
   
{% include 'nav.html' %}


{% block content %}
  
{% endblock content %}

</body>
</html>

hosting/templates/hosting/my_bookings.html
{% include 'topnav.html' %}


{% if my_bookings  %}

{% for booking in my_bookings  %}
<p>{{booking}}</p>
{% endfor %}

{% else %}
<p>No booking for your listed rooms yet</p>
{% endif %}
    

hosting/templates/hosting/nav.html
{% load static %} 

<link rel="stylesheet" type="text/css" href="{%  static 'hosting/nav.css' %}">

<div class="nav">
    <a href="" class="navlink"> <img src="{% static 'hosting/images/home.svg' %}" alt="home" class="svg">HOME</a>
    <a href="{% url 'hosting:view-rooms' %}" class="navlink"><img src="{% static 'hosting/images/list.svg' %}" alt="room" class="svg">ROOMS</a>
    <a href="" class="navlink"><img src="{% static 'hosting/images/book.svg' %}" alt="book" class="svg">BOOK</a>
    <a href="" class="navlink"><img src="{% static 'hosting/images/contact.svg' %}" alt="contact" class="svg">CONTACT</a>

</div>

hosting/templates/hosting/room_detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'hosting/roomdetail.css' %}">
{% block title %}
<script>
    function goBack() {
      window.history.back();
    }
    </script>
    <button class="go-back" onclick="goBack()">Go Back</button>

<div class="card">
 
    <img src="{{room.image.url}}" alt="room image" class="img" style="width:100%;height: 100%;">
    <div class="container">
        <h2>{{room.name}}</h2>
        

      <p>Description: {{room.description}}</p>
      <h4 class="price"><b>Price USD: {{room.price}}</b></h4>
      <h4>Location: {{room.location}}</h4>
      {% if request.user == room.owner %}
      <button class="button"  onclick="window.location.href='{% url 'hosting:editroom' room.id %}'"  >EDIT</button>
      {% else %}
      
      <button class="button"  onclick="window.location.href='{% url 'hosting:book-room' room.id request.user.id %}'"  >Book</button>
      
      {% endif %}
      
    
    </div>
  </div>

{% endblock title %}

hosting/templates/hosting/search.html
{% load static  %}


<link rel="stylesheet" type="text/css" href="{%  static 'hosting/search.css' %}">

<form class="nosubmit" method="post" >
    {% csrf_token %}
    <input class="nosubmit" type="search" placeholder="Search...">
</form>

hosting/templates/hosting/topnav.html
{% load static  %}

<link rel="stylesheet" href="{% static 'hosting/topnav.css' %}">

<div class="topnav">
    <a class="active" href="{% url 'hosting:dashboard'%}">Home</a>
    <a href="{% url 'hosting:dashboard' %}">My Rooms</a>
    <a href="{%  url 'hosting:show-my-bookings' %}">My Bookings</a>
    <a href="#about">About</a>
    {% if request.user.is_authenticated %}

    <a href="{% url 'accounts:logout' %}" id="logout">Logout</a>
      
    {% endif %}
</div>